INSERT INTO `bookinventory`(
    `
book_id`,
`book_name
`,
    `book_image`,
    `book_author`,
    `book_price`,
    `book_serial_number`
)
VALUES
(
    '1',
    'Who Moved My Cheese?',
    'https://images-na.ssl-images-amazon.com/images/I/91yj3mbz4JL.jpg',
    'Spencer Johnson',
    '27.99',
    '73856859',
    '8'
),
(
    '2',
    'The story of My Experiments with Truth',
    'https://images-na.ssl-images-amazon.com/images/I/51YFY2uXjpL.jpg',
    'Mahatma Gandhi',
    '45.99',
    '46533694',
    '6'
),
(
    '3',
    'The Intelligent Investor',
    'https://images-na.ssl-images-amazon.com/images/I/91yj3mbz4JL.jpg',
    'Benjamin Graham',
    '63.00',
    '89695866',
    '7'
),
(
    '4',
    'Zero to One',
    'https://images-na.ssl-images-amazon.com/images/I/71Xygne8+qL.jpg',
    'Blake Masters and Peter Thiel',
    '27.99',
    '45559599',
    '4'
),
(
    '5',
    'Letters from an Astrophysicist',
    'https://images-na.ssl-images-amazon.com/images/I/61vxo7vrGeL.jpg',
    'Neil deGrasse Tyson',
    '81.99',
    '54372872',
    '5'
);



